# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish_data',
            new_name='published_date',
        ),
    ]
